//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Successes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Successes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Successes", typeof(Successes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully created..
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully deleted..
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired product has been added to the cart.
        /// </summary>
        public static string Thedesiredproducthasbeenaddedtothecart {
            get {
                return ResourceManager.GetString("Thedesiredproducthasbeenaddedtothecart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item has been successfully removed from your shopping cart.
        /// </summary>
        public static string Theitemhasbeensuccessfullyremovedfromyourshoppingcart {
            get {
                return ResourceManager.GetString("Theitemhasbeensuccessfullyremovedfromyourshoppingcart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully updated..
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully verified..
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have logged out of your account.
        /// </summary>
        public static string Youhaveloggedoutofyouraccount {
            get {
                return ResourceManager.GetString("Youhaveloggedoutofyouraccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information has been edited successfully.
        /// </summary>
        public static string Yourinformationhasbeeneditedsuccessfully {
            get {
                return ResourceManager.GetString("Yourinformationhasbeeneditedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer, your purchase has been successfully registered. It will be sent and informed in the next few days. Thank you for choosing Mallika Bano gallery to buy..
        /// </summary>
        public static string Youritemhasbeenregistered {
            get {
                return ResourceManager.GetString("Youritemhasbeenregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been registered.
        /// </summary>
        public static string Yourorderhasbeenregistered {
            get {
                return ResourceManager.GetString("Yourorderhasbeenregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration has been completed.
        /// </summary>
        public static string Yourregistrationhasbeencompleted {
            get {
                return ResourceManager.GetString("Yourregistrationhasbeencompleted", resourceCulture);
            }
        }
    }
}
